### ISSUE TITLE
The 4.0 version completely ruined its usability. 

### ISSUE THREAD

**Issue by JohnTitor120** [dmstern/likers-blocker#148]
Slow 500 limit, multiple logins required even on slow settings, inefficient as fuck when it comes to blocking.

The links on v3.1.5 were better, they were faster, you could block tens of thousands in the time it takes to block 500. Not to mention the multiple account locks that are coming from the addon now all of a sudden, was never an issue before.

Absolute trash, you fucking ruined it. 

Fix the https://ichbinhier-twittertools.herokuapp.com/ website so I can use the non-shit version again.

**Comment by JohnTitor120** [comment]
As of now Red Block is a superior tool. 

Has the same 500 limit but goes quick, one button reset, followers and mutual exemptions, and so far no lockout.

**Comment by dmstern** [comment]
Dear John,

thank you for your kind feedback, we really appreciate it. Please consider blaming Elon Musk since Twitter decided to discontinue the free API usage under his leadership. Read the [release notes](https://github.com/dmstern/likers-blocker/releases/tag/v4.0.0). And please consider attending a yoga class.

Kind regards,
Daniel

**Comment by JohnTitor120** [comment]
Ah, so it's really just petty bullshit on your part.
