### ISSUE TITLE
it merely hides the likers but doesn't block them

### ISSUE THREAD

**Issue by sterelok123** [dmstern/likers-blocker#58]
hi. after experimenting, i realized the app only manages to find a few likers and blocked thoes maybe. but it keeps showing there are no likers when i check the likes when there are thousands of likers. it is wrong. ican't see the likers now to block them myself!!

**Comment by dmstern** [comment]
Hi @sterelok123,

this is a problem with the Twitter UI / API. Their UI limits us to a maximum of 80 likers that are shown in the list. If you block those first 80 users (either by yourself or with the extension), Twitter does not show them anymore in the list nor can we fetch them via the API due to that limit.
I am sorry, but unfortunately, we can not do anything to fix this until Twitter opens its API to get more likers from the server.
