### ISSUE TITLE
Not working in Edge

### ISSUE THREAD

**Issue by nichu42** [dmstern/likers-blocker#72]
Hey there,

Since the original issue has been closed in the meantime, I'm opening up a new one.
Likers Blocker is still not working for me on MS Edge Chromium.

It scrolls to the end of the list but doesn't do anything than showing the three animated dots.
It doesn't matter how many likers or retweeters the tweet has. I tried with 10, 50, 100.... No luck.

Just as an example: Tweet has 48 likers. The plugin scrolls to the very end of the list, but shows 45 likes only. It does not proceed from there.

I'm on Build 100.0.1169.1

I'd really love to use the extension again - it worked perfectly in the past.

Thank you for any help!

Nic

**Comment by dmstern** [comment]
Hey @nichu42,

unfortunately I can not reproduce this issue. I tried just now with MS Edge build 99.0.1150.36 and the current LikersBlocker version with a tweet of 2 likes and a tweet of 160 likes. Both work.
But there is a similar issue: #73 where we have a problem with large likers lists. Is this maybe related to your problem? Honestly I don't think so since you said you also tried with small like lists... 🤔

**Comment by dmstern** [comment]
@nichu42 could you please try if the issue is fixed by the new major release? https://github.com/dmstern/likers-blocker/releases

It's not yet in the Chrome web store but you can install it locally as described in the release notes.

**Comment by nichu42** [comment]
@dmstern: Thank you very much for looking into this. Whatever you did, it helped! I can finally use the extension again. Thanks!

**Comment by dmstern** [comment]
Great to hear! :)
