### ISSUE TITLE
Suggestion: Followers Blocker

### ISSUE THREAD

**Issue by Taberone** [dmstern/likers-blocker#84]
I'd love for a "Followers Blocker" that works the same way Likers Blocker does. Sometimes you need to block everyone who follows someone, not just anyone who likes their tweet.

**Comment by mitzel** [comment]
Additionally a "followed by Blocker" would be nice. I don't want to see anything about users which are followed by [@IdiotenD](https://twitter.com/IdiotenD) or users who blocked this account.

**Comment by kokabi1365** [comment]
And the next step can be chain Blocker. That means when I block someone's followers I also expect to block their folowers's followers and also folowers's follower's followers's ... until the end of chain.

**Comment by dmstern** [comment]
There are already some good follower-blockers out there. The problem with follower blockers is the risk of too many false-positives. Some people follow several accounts to watch their activity without the aim to support them (fair enough: in my opinion, this is also quite problematic, because a larger number of followers is also some kind of support and there are other possibilities to keep an eye on specific accounts).

With Likers Blocker, we wanted to create a tool that automates the block process based on their activity, on the content they post, on the things they say and what they actively support, not by judging them for who they are or who they follow.
Block automatization should be used with causion. 

Please checkout [RedBlock](https://github.com/gaeulbyul/RedBlock) or [Twitter Block Chain](https://github.com/ceceradio/twitter-block-chain) they do a really good job.

I hope you can understand this. :)

I will close this as `won't fix`.
