### ISSUE TITLE
compress users list?

### ISSUE THREAD

**Issue by wchristian** [dmstern/likers-blocker#91]
As a quick intermediate solution to reduce the amounts of block lists, maybe do something like gz + base64 encode to transmit the list in a compressed format?

**Comment by dmstern** [comment]
Hi @wchristian, thanks for your suggestion!  
Unfortunately, this would probably not really fix it, since the users list won't get smaller by base64 encoding it. I currently do not know if compression would have a greater effect but I already prepared a solution to avoid the url lenght limit issue: #88 and I think the idea of completely get rid of the list url parameter is an even better approach for the user. This is currently blocked by a back-end adaption.
If you have other information or more ideas, feel free to comment. :)
Until then I'll close this.

**Comment by wchristian** [comment]
Keep in mind i said gz + base64. :)

That said, local storage as a buffer does seem like a much more useful way to do this, so i'm looking forward to it.

In the meantime i'm using tampermonkey scripts to speed up the process. :D
